name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Download FortiClient SSLVPN CLI
      run: |
        wget http://cdn.software-mirrors.com/forticlientsslvpn_linux_4.4.2328.tar.gz
        tar -xzvf forticlientsslvpn_linux_4.4.2328.tar.gz
        sudo apt-get install ppp
        cd ./forticlientsslvpn/64bit/helper
        sudo ./setup.linux.sh
        cd ../..
    - name: Connect to FortiClient VPN
      run: |
        ./forticlientsslvpn/64bit/forticlientsslvpn_cli --server ${serveraddress}:443 --vpnuser ${{secrets.username}} --vpnpass ${{secrets.password}} &
        sleep 20 # Adjust delay as needed
        VPN_STATUS=$(ps aux | grep forticlientsslvpn_cli | grep -v grep | wc -l)
        if [ "$VPN_STATUS" -gt 0 ]; then
          echo "VPN Connected successfully."
        else
          echo "VPN connection failed."
          exit 1
        fi
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
